# name of the software
name: jQuery highlightTextarea
# current version of the software
version: 3.1.3
# url of the download button
downloadUrl: https://github.com/garysieling/jquery-highlighttextarea
# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/garysieling/jquery-highlighttextarea
  - title: StrangePlanet
    url: http://www.strangeplanet.fr
  - title: Gary Sieling
    url: https://www.garysieling.com/blog

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/garysieling/jquery-highlighttextarea
  - title: Issues
    url: https://github.com/garysieling/jquery-highlighttextarea/issues?state=open

# header
header:
  color1: "#cc6c00"
  color2: "#9b1b17"
  trianglify: true

# github button
githubButton:
  user: garysieling
  repo: jquery-highlighttextarea

# twitter buttons
twitter:
  enabled: true
  via: garysieling
  hash:
  account:

# facebook buttons
facebook:
  enabled: true
  profileUrl:

# google analytics
analytics:
  account: UA-11508275-5
  domain: garysieling.github.io


# DON'T MODIFY
pygments: true
highlight: pygments

exclude: ['README.md', 'Gemfile.lock', 'Gemfile']
